_BASE_: "Base-DiffusionDet.yaml"
MODEL:
  WEIGHTS: "models/torchvision-R-101.pkl"
  RESNETS:
    DEPTH: 101
    STRIDE_IN_1X1: False
  DiffusionDet:
    NUM_PROPOSALS: 500
    NUM_CLASSES: 80
    THRESHOLD: 0.1
    PLOT_BOXES: False
DATASETS:
  TRAIN: ("visdrone_train",)
  TEST:  ("visdrone_val",)
SOLVER:
  STEPS: (350000, 420000)
  MAX_ITER: 450000
INPUT:
  CROP:
    ENABLED: True
  FORMAT: "RGB"
